# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fbc4d983f5c6c3a807dbbee5aa1a2f38812dc4a6f58ff12aeb9cf6b85519a100b6268a6b3f5e3513a2a37fe8b1b2a8ab8aab16f79c97adcf4097c5b128e647e

test:
  secret_key_base: 73fc94131ec62a02ef469641dffdac6fe7a7bcd528a3d63cc0b637d50aa646181ccff00c7d872dc34bd7ae06fdf0156e8ac30928eb7f0e405b0fa90556d11fb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
